# Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: ""
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DATABASE: animal_shelter

# Server Config
ACTIVE_PROFILE: prod

#Token Config
JWT_SECRET: "r{yGsuYn7k9[qs&"